### ISSUE TITLE
Website blocked by Censors

### ISSUE THREAD

**Issue by reelsense** [3rd-stone/AWS-url-shorten-serverless-application-pipeline#1]
Your website was blocked gov. censors.

<img width="974" alt="Screen Shot 2020-06-04 at 19 28 55" src="https://user-images.githubusercontent.com/5644977/83830495-2db17380-a69a-11ea-90ba-7c084e37681b.png">

**Comment by 3rd-stone** [comment]
sorry but my domain will be expired, you may view the demo through https://nvj8cs7lw5.execute-api.us-east-1.amazonaws.com/Stage
